print("################################################")
print("False and False = ",(False and False))
print("False and True = ", (False and True))
print("True and False = ", (True and False))
print("True and True = ", (True and True))
print("################################################")
print("not (False and False) = ", not (False and False))
print("not (False and True) = ", not (False and True))
print("not (True and False) = ", not (True and False))
print("not (True and True) = ", not (True and True))
print("################################################")
print("False or False = ",(False or False))
print("False or True = ", (False or True))
print("True or False = ", (True or False))
print("True or True = ", (True or True))
print("################################################")
print("not (False or False) = ", not (False or False))
print("not (False or True) = ", not (False or True))
print("not (True or False) = ", not (True or False))
print("not (True or True) = ", not (True or True))